#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cd "$(dirname "$0")/.."

echo "Buildeando la aplicación..."
dotnet build Tienda.csproj --no-restore --verbosity quiet

echo "Chequeo del pre-push completado"

